// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: antsimulator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_START        CommandType = 0
	CommandType_PAUSE        CommandType = 1
	CommandType_RESET        CommandType = 2
	CommandType_SPAWN_FOOD   CommandType = 3 // Legacy?
	CommandType_SPAWN_PLANT  CommandType = 4
	CommandType_SPAWN_ANIMAL CommandType = 5
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "START",
		1: "PAUSE",
		2: "RESET",
		3: "SPAWN_FOOD",
		4: "SPAWN_PLANT",
		5: "SPAWN_ANIMAL",
	}
	CommandType_value = map[string]int32{
		"START":        0,
		"PAUSE":        1,
		"RESET":        2,
		"SPAWN_FOOD":   3,
		"SPAWN_PLANT":  4,
		"SPAWN_ANIMAL": 5,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_antsimulator_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_antsimulator_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_antsimulator_proto_rawDescGZIP(), []int{0}
}

type AntRole int32

const (
	AntRole_QUEEN   AntRole = 0
	AntRole_WORKER  AntRole = 1
	AntRole_SOLDIER AntRole = 2
)

// Enum value maps for AntRole.
var (
	AntRole_name = map[int32]string{
		0: "QUEEN",
		1: "WORKER",
		2: "SOLDIER",
	}
	AntRole_value = map[string]int32{
		"QUEEN":   0,
		"WORKER":  1,
		"SOLDIER": 2,
	}
)

func (x AntRole) Enum() *AntRole {
	p := new(AntRole)
	*p = x
	return p
}

func (x AntRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AntRole) Descriptor() protoreflect.EnumDescriptor {
	return file_antsimulator_proto_enumTypes[1].Descriptor()
}

func (AntRole) Type() protoreflect.EnumType {
	return &file_antsimulator_proto_enumTypes[1]
}

func (x AntRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AntRole.Descriptor instead.
func (AntRole) EnumDescriptor() ([]byte, []int) {
	return file_antsimulator_proto_rawDescGZIP(), []int{1}
}

type AntState int32

const (
	AntState_IDLE                AntState = 0
	AntState_EXPLORING           AntState = 1
	AntState_RETURNING_WITH_FOOD AntState = 2
)

// Enum value maps for AntState.
var (
	AntState_name = map[int32]string{
		0: "IDLE",
		1: "EXPLORING",
		2: "RETURNING_WITH_FOOD",
	}
	AntState_value = map[string]int32{
		"IDLE":                0,
		"EXPLORING":           1,
		"RETURNING_WITH_FOOD": 2,
	}
)

func (x AntState) Enum() *AntState {
	p := new(AntState)
	*p = x
	return p
}

func (x AntState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AntState) Descriptor() protoreflect.EnumDescriptor {
	return file_antsimulator_proto_enumTypes[2].Descriptor()
}

func (AntState) Type() protoreflect.EnumType {
	return &file_antsimulator_proto_enumTypes[2]
}

func (x AntState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AntState.Descriptor instead.
func (AntState) EnumDescriptor() ([]byte, []int) {
	return file_antsimulator_proto_rawDescGZIP(), []int{2}
}

type ResourceType int32

const (
	ResourceType_PLANT  ResourceType = 0
	ResourceType_ANIMAL ResourceType = 1
)

// Enum value maps for ResourceType.
var (
	ResourceType_name = map[int32]string{
		0: "PLANT",
		1: "ANIMAL",
	}
	ResourceType_value = map[string]int32{
		"PLANT":  0,
		"ANIMAL": 1,
	}
)

func (x ResourceType) Enum() *ResourceType {
	p := new(ResourceType)
	*p = x
	return p
}

func (x ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_antsimulator_proto_enumTypes[3].Descriptor()
}

func (ResourceType) Type() protoreflect.EnumType {
	return &file_antsimulator_proto_enumTypes[3]
}

func (x ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceType.Descriptor instead.
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_antsimulator_proto_rawDescGZIP(), []int{3}
}

type RoomType int32

const (
	RoomType_ROYAL   RoomType = 0
	RoomType_GRANARY RoomType = 1
	RoomType_NURSERY RoomType = 2
)

// Enum value maps for RoomType.
var (
	RoomType_name = map[int32]string{
		0: "ROYAL",
		1: "GRANARY",
		2: "NURSERY",
	}
	RoomType_value = map[string]int32{
		"ROYAL":   0,
		"GRANARY": 1,
		"NURSERY": 2,
	}
)

func (x RoomType) Enum() *RoomType {
	p := new(RoomType)
	*p = x
	return p
}

func (x RoomType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomType) Descriptor() protoreflect.EnumDescriptor {
	return file_antsimulator_proto_enumTypes[4].Descriptor()
}

func (RoomType) Type() protoreflect.EnumType {
	return &file_antsimulator_proto_enumTypes[4]
}

func (x RoomType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomType.Descriptor instead.
func (RoomType) EnumDescriptor() ([]byte, []int) {
	return file_antsimulator_proto_rawDescGZIP(), []int{4}
}

type CommandRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Command CommandType            `protobuf:"varint,1,opt,name=command,proto3,enum=antsimulator.CommandType" json:"command,omitempty"`
	// Paramètres optionnels pour l'interaction dynamique
	X             *float32 `protobuf:"fixed32,2,opt,name=x,proto3,oneof" json:"x,omitempty"`
	Y             *float32 `protobuf:"fixed32,3,opt,name=y,proto3,oneof" json:"y,omitempty"`
	Amount        *int32   `protobuf:"varint,4,opt,name=amount,proto3,oneof" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_antsimulator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antsimulator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_antsimulator_proto_rawDescGZIP(), []int{0}
}

func (x *CommandRequest) GetCommand() CommandType {
	if x != nil {
		return x.Command
	}
	return CommandType_START
}

func (x *CommandRequest) GetX() float32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *CommandRequest) GetY() float32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *CommandRequest) GetAmount() int32 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_antsimulator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antsimulator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_antsimulator_proto_rawDescGZIP(), []int{1}
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Demande une fréquence de mise à jour spécifique (ex: 30 fps)
	TargetTps     int32 `protobuf:"varint,1,opt,name=target_tps,json=targetTps,proto3" json:"target_tps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_antsimulator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antsimulator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_antsimulator_proto_rawDescGZIP(), []int{2}
}

func (x *StreamRequest) GetTargetTps() int32 {
	if x != nil {
		return x.TargetTps
	}
	return 0
}

type Ant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          AntRole                `protobuf:"varint,2,opt,name=role,proto3,enum=antsimulator.AntRole" json:"role,omitempty"`
	X             float32                `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	State         AntState               `protobuf:"varint,5,opt,name=state,proto3,enum=antsimulator.AntState" json:"state,omitempty"`
	Angle         float32                `protobuf:"fixed32,6,opt,name=angle,proto3" json:"angle,omitempty"`
	FactionId     uint32                 `protobuf:"varint,7,opt,name=faction_id,json=factionId,proto3" json:"faction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ant) Reset() {
	*x = Ant{}
	mi := &file_antsimulator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ant) ProtoMessage() {}

func (x *Ant) ProtoReflect() protoreflect.Message {
	mi := &file_antsimulator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ant.ProtoReflect.Descriptor instead.
func (*Ant) Descriptor() ([]byte, []int) {
	return file_antsimulator_proto_rawDescGZIP(), []int{3}
}

func (x *Ant) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Ant) GetRole() AntRole {
	if x != nil {
		return x.Role
	}
	return AntRole_QUEEN
}

func (x *Ant) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Ant) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Ant) GetState() AntState {
	if x != nil {
		return x.State
	}
	return AntState_IDLE
}

func (x *Ant) GetAngle() float32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

func (x *Ant) GetFactionId() uint32 {
	if x != nil {
		return x.FactionId
	}
	return 0
}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Quantity      uint32                 `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"` // Diminue quand les fourmis récoltent
	Type          ResourceType           `protobuf:"varint,5,opt,name=type,proto3,enum=antsimulator.ResourceType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_antsimulator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_antsimulator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_antsimulator_proto_rawDescGZIP(), []int{4}
}

func (x *Resource) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Resource) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Resource) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Resource) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Resource) GetType() ResourceType {
	if x != nil {
		return x.Type
	}
	return ResourceType_PLANT
}

type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomType      RoomType               `protobuf:"varint,2,opt,name=room_type,json=roomType,proto3,enum=antsimulator.RoomType" json:"room_type,omitempty"`
	X             float32                `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	Radius        float32                `protobuf:"fixed32,5,opt,name=radius,proto3" json:"radius,omitempty"` // Taille de la pièce
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_antsimulator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_antsimulator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_antsimulator_proto_rawDescGZIP(), []int{5}
}

func (x *Room) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Room) GetRoomType() RoomType {
	if x != nil {
		return x.RoomType
	}
	return RoomType_ROYAL
}

func (x *Room) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Room) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Room) GetRadius() float32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

type Nest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FactionId     uint32                 `protobuf:"varint,1,opt,name=faction_id,json=factionId,proto3" json:"faction_id,omitempty"`
	Rooms         []*Room                `protobuf:"bytes,2,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nest) Reset() {
	*x = Nest{}
	mi := &file_antsimulator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nest) ProtoMessage() {}

func (x *Nest) ProtoReflect() protoreflect.Message {
	mi := &file_antsimulator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nest.ProtoReflect.Descriptor instead.
func (*Nest) Descriptor() ([]byte, []int) {
	return file_antsimulator_proto_rawDescGZIP(), []int{6}
}

func (x *Nest) GetFactionId() uint32 {
	if x != nil {
		return x.FactionId
	}
	return 0
}

func (x *Nest) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type GameState struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Tick      uint64                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Ants      []*Ant                 `protobuf:"bytes,2,rep,name=ants,proto3" json:"ants,omitempty"`
	Resources []*Resource            `protobuf:"bytes,3,rep,name=resources,proto3" json:"resources,omitempty"`
	Nests     []*Nest                `protobuf:"bytes,4,rep,name=nests,proto3" json:"nests,omitempty"`
	// Optimisation : La carte des phéromones est envoyée sous forme de bytes compressés
	// (ex: run-length encoding ou un simple flat array) pour éviter l'overhead de la sérialisation d'objets imbriqués.
	EncodedPheromones []byte `protobuf:"bytes,5,opt,name=encoded_pheromones,json=encodedPheromones,proto3" json:"encoded_pheromones,omitempty"`
	MapSeed           uint64 `protobuf:"varint,6,opt,name=map_seed,json=mapSeed,proto3" json:"map_seed,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_antsimulator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_antsimulator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_antsimulator_proto_rawDescGZIP(), []int{7}
}

func (x *GameState) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *GameState) GetAnts() []*Ant {
	if x != nil {
		return x.Ants
	}
	return nil
}

func (x *GameState) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *GameState) GetNests() []*Nest {
	if x != nil {
		return x.Nests
	}
	return nil
}

func (x *GameState) GetEncodedPheromones() []byte {
	if x != nil {
		return x.EncodedPheromones
	}
	return nil
}

func (x *GameState) GetMapSeed() uint64 {
	if x != nil {
		return x.MapSeed
	}
	return 0
}

var File_antsimulator_proto protoreflect.FileDescriptor

const file_antsimulator_proto_rawDesc = "" +
	"\n" +
	"\x12antsimulator.proto\x12\fantsimulator\"\x9f\x01\n" +
	"\x0eCommandRequest\x123\n" +
	"\acommand\x18\x01 \x01(\x0e2\x19.antsimulator.CommandTypeR\acommand\x12\x11\n" +
	"\x01x\x18\x02 \x01(\x02H\x00R\x01x\x88\x01\x01\x12\x11\n" +
	"\x01y\x18\x03 \x01(\x02H\x01R\x01y\x88\x01\x01\x12\x1b\n" +
	"\x06amount\x18\x04 \x01(\x05H\x02R\x06amount\x88\x01\x01B\x04\n" +
	"\x02_xB\x04\n" +
	"\x02_yB\t\n" +
	"\a_amount\"E\n" +
	"\x0fCommandResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\".\n" +
	"\rStreamRequest\x12\x1d\n" +
	"\n" +
	"target_tps\x18\x01 \x01(\x05R\ttargetTps\"\xbf\x01\n" +
	"\x03Ant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12)\n" +
	"\x04role\x18\x02 \x01(\x0e2\x15.antsimulator.AntRoleR\x04role\x12\f\n" +
	"\x01x\x18\x03 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x02R\x01y\x12,\n" +
	"\x05state\x18\x05 \x01(\x0e2\x16.antsimulator.AntStateR\x05state\x12\x14\n" +
	"\x05angle\x18\x06 \x01(\x02R\x05angle\x12\x1d\n" +
	"\n" +
	"faction_id\x18\a \x01(\rR\tfactionId\"\x82\x01\n" +
	"\bResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\rR\bquantity\x12.\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1a.antsimulator.ResourceTypeR\x04type\"\x7f\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x123\n" +
	"\troom_type\x18\x02 \x01(\x0e2\x16.antsimulator.RoomTypeR\broomType\x12\f\n" +
	"\x01x\x18\x03 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x02R\x01y\x12\x16\n" +
	"\x06radius\x18\x05 \x01(\x02R\x06radius\"O\n" +
	"\x04Nest\x12\x1d\n" +
	"\n" +
	"faction_id\x18\x01 \x01(\rR\tfactionId\x12(\n" +
	"\x05rooms\x18\x02 \x03(\v2\x12.antsimulator.RoomR\x05rooms\"\xf0\x01\n" +
	"\tGameState\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x04R\x04tick\x12%\n" +
	"\x04ants\x18\x02 \x03(\v2\x11.antsimulator.AntR\x04ants\x124\n" +
	"\tresources\x18\x03 \x03(\v2\x16.antsimulator.ResourceR\tresources\x12(\n" +
	"\x05nests\x18\x04 \x03(\v2\x12.antsimulator.NestR\x05nests\x12-\n" +
	"\x12encoded_pheromones\x18\x05 \x01(\fR\x11encodedPheromones\x12\x19\n" +
	"\bmap_seed\x18\x06 \x01(\x04R\amapSeed*a\n" +
	"\vCommandType\x12\t\n" +
	"\x05START\x10\x00\x12\t\n" +
	"\x05PAUSE\x10\x01\x12\t\n" +
	"\x05RESET\x10\x02\x12\x0e\n" +
	"\n" +
	"SPAWN_FOOD\x10\x03\x12\x0f\n" +
	"\vSPAWN_PLANT\x10\x04\x12\x10\n" +
	"\fSPAWN_ANIMAL\x10\x05*-\n" +
	"\aAntRole\x12\t\n" +
	"\x05QUEEN\x10\x00\x12\n" +
	"\n" +
	"\x06WORKER\x10\x01\x12\v\n" +
	"\aSOLDIER\x10\x02*<\n" +
	"\bAntState\x12\b\n" +
	"\x04IDLE\x10\x00\x12\r\n" +
	"\tEXPLORING\x10\x01\x12\x17\n" +
	"\x13RETURNING_WITH_FOOD\x10\x02*%\n" +
	"\fResourceType\x12\t\n" +
	"\x05PLANT\x10\x00\x12\n" +
	"\n" +
	"\x06ANIMAL\x10\x01*/\n" +
	"\bRoomType\x12\t\n" +
	"\x05ROYAL\x10\x00\x12\v\n" +
	"\aGRANARY\x10\x01\x12\v\n" +
	"\aNURSERY\x10\x022\xa6\x01\n" +
	"\x11SimulationService\x12J\n" +
	"\vSendCommand\x12\x1c.antsimulator.CommandRequest\x1a\x1d.antsimulator.CommandResponse\x12E\n" +
	"\vStreamState\x12\x1b.antsimulator.StreamRequest\x1a\x17.antsimulator.GameState0\x01B\tZ\a./protob\x06proto3"

var (
	file_antsimulator_proto_rawDescOnce sync.Once
	file_antsimulator_proto_rawDescData []byte
)

func file_antsimulator_proto_rawDescGZIP() []byte {
	file_antsimulator_proto_rawDescOnce.Do(func() {
		file_antsimulator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_antsimulator_proto_rawDesc), len(file_antsimulator_proto_rawDesc)))
	})
	return file_antsimulator_proto_rawDescData
}

var file_antsimulator_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_antsimulator_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_antsimulator_proto_goTypes = []any{
	(CommandType)(0),        // 0: antsimulator.CommandType
	(AntRole)(0),            // 1: antsimulator.AntRole
	(AntState)(0),           // 2: antsimulator.AntState
	(ResourceType)(0),       // 3: antsimulator.ResourceType
	(RoomType)(0),           // 4: antsimulator.RoomType
	(*CommandRequest)(nil),  // 5: antsimulator.CommandRequest
	(*CommandResponse)(nil), // 6: antsimulator.CommandResponse
	(*StreamRequest)(nil),   // 7: antsimulator.StreamRequest
	(*Ant)(nil),             // 8: antsimulator.Ant
	(*Resource)(nil),        // 9: antsimulator.Resource
	(*Room)(nil),            // 10: antsimulator.Room
	(*Nest)(nil),            // 11: antsimulator.Nest
	(*GameState)(nil),       // 12: antsimulator.GameState
}
var file_antsimulator_proto_depIdxs = []int32{
	0,  // 0: antsimulator.CommandRequest.command:type_name -> antsimulator.CommandType
	1,  // 1: antsimulator.Ant.role:type_name -> antsimulator.AntRole
	2,  // 2: antsimulator.Ant.state:type_name -> antsimulator.AntState
	3,  // 3: antsimulator.Resource.type:type_name -> antsimulator.ResourceType
	4,  // 4: antsimulator.Room.room_type:type_name -> antsimulator.RoomType
	10, // 5: antsimulator.Nest.rooms:type_name -> antsimulator.Room
	8,  // 6: antsimulator.GameState.ants:type_name -> antsimulator.Ant
	9,  // 7: antsimulator.GameState.resources:type_name -> antsimulator.Resource
	11, // 8: antsimulator.GameState.nests:type_name -> antsimulator.Nest
	5,  // 9: antsimulator.SimulationService.SendCommand:input_type -> antsimulator.CommandRequest
	7,  // 10: antsimulator.SimulationService.StreamState:input_type -> antsimulator.StreamRequest
	6,  // 11: antsimulator.SimulationService.SendCommand:output_type -> antsimulator.CommandResponse
	12, // 12: antsimulator.SimulationService.StreamState:output_type -> antsimulator.GameState
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_antsimulator_proto_init() }
func file_antsimulator_proto_init() {
	if File_antsimulator_proto != nil {
		return
	}
	file_antsimulator_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_antsimulator_proto_rawDesc), len(file_antsimulator_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_antsimulator_proto_goTypes,
		DependencyIndexes: file_antsimulator_proto_depIdxs,
		EnumInfos:         file_antsimulator_proto_enumTypes,
		MessageInfos:      file_antsimulator_proto_msgTypes,
	}.Build()
	File_antsimulator_proto = out.File
	file_antsimulator_proto_goTypes = nil
	file_antsimulator_proto_depIdxs = nil
}
