apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: apps
  labels:
    app: gateway
spec:
  replicas: 3 # Gateway is stateless and can scale horizontally
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: ${IMAGE_GATEWAY}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        # DNS name of the engine service in k8s
        - name: ENGINE_ADDR
          value: "engine:50051"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: apps
spec:
  selector:
    app: gateway
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
